name = "ngaji-tracker"
main = "worker.js"
compatibility_date = "2026-09-21"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ngaji-tracker-db"
database_id = "a48bd050-29f1-4551-835d-a37c9db244d5"
migrations_dir = "migrations"
